#!/usr/bin/env bash
blue="\e[0;94m"
color_reset="\e[0m"
    echo "commands:"
    echo "    project"
    tree "$FORNIX_COMMANDS_FOLDER/project" -C --dirsfirst -A -F --noreport | sed 's/^/     /' | sed -E 's/(\*|@)$/ /' | sed "1d"
    echo "    run"
    tree "$FORNIX_COMMANDS_FOLDER/run" -C --dirsfirst -A -F --noreport | sed 's/^/     /' | sed -E 's/(\*|@)$/ /' | sed "1d"
    echo 
    echo "example commands:"
    printf "$blue"
    echo "    run autograder search_agent"
    echo "    run pacman"
    echo "    project commands"
    printf "$color_reset"
    
